const seeds = [
  { text: "Meditate" },
  { text: "Drink 8 glasses of water" },
  { text: "Take a walk in nature" },
  { text: "Write a journal" },
  { text: "Read a book" },
  { text: "Call an old friend" },
  { text: "Go for a run" },
  { text: "Eat 5 fruit and veg" },
  { text: "Learn some phrases in a new language" },
  { text: "Start to learn a new skill" },
  { text: "Organise a games night" },
  { text: "Make / Craft something yourself" },
  { text: "Take a break from your mobile" },
  { text: 'Get some "me" time' },
  { text: "Savour a cup of tea or coffee" },
  { text: "Do some yoga" },
  { text: "Cook something from scratch" },
  { text: "Explore a new place" },
  { text: "Do some decluttering" },
  { text: "Become a volunteer" },
  { text: "Give some old clothes or other items to charity" },
  { text: "Do a random act of kindness" },
  { text: "Start a new hobby" },
  { text: "Start learning to play a musical instrument" },
  { text: "Listen to music" },
  { text: "Notice the feel of the wind or the sun on your skin" },
  { text: "Find a mentor" },
  { text: "Buy more cheeze!" }
]

module.exports = seeds;
